rss_feeds:
  - "https://news.google.com/rss/search?q=site:reuters.com%20India&hl=en-IN&gl=IN&ceid=IN:en"
  - "https://news.google.com/rss/search?q=site:economictimes.indiatimes.com%20markets&hl=en-IN&gl=IN&ceid=IN:en"
  - "https://news.google.com/rss/search?q=site:moneycontrol.com%20news&hl=en-IN&gl=IN&ceid=IN:en"
  - "https://news.google.com/rss/search?q=site:livemint.com%20markets&hl=en-IN&gl=IN&ceid=IN:en"

# optional allowlist of publishers (substring match on final URL)
publisher_allowlist:
  - reuters.com
  - economictimes.indiatimes.com
  - moneycontrol.com
  - livemint.com

# polite delay (in seconds) between resolving article URLs
resolve_delay_seconds: 0.35

max_items_per_feed: 100
